@baseUrl = http://localhost:3000/api

### PASS
GET {{baseUrl}}/product/item/20 HTTP/1.1
### PASS
GET {{baseUrl}}/product/quantity/1 HTTP/1.1

### PASS
GET {{baseUrl}}/import?status=PENDING HTTP/1.1

### PASS nhất định cần productId
POST {{baseUrl}}/import HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "itemId": 100,
            "productId":1,
            "goodQuantity": 5,
            "badQuantity":0
        },
        {
            "itemId": 20,
            "productId":3,
            "goodQuantity": 5,
            "badQuantity":0
        }
    ]
}
### PASS
GET {{baseUrl}}/export?status=PENDING HTTP/1.1

### PASS nhất định cần productId
POST {{baseUrl}}/export HTTP/1.1
Content-Type: application/json

{
    "items": [
        {
            "itemId": 1,
            "productId":1,
            "goodQuantity": 5,
            "badQuantity":0
        }
    ]
}

### PASS  Trả lại 1 danh sách các historyItem 
GET {{baseUrl}}/export/3 HTTP/1.1
### PASS 
PATCH  {{baseUrl}}/export/57 HTTP/1.1
Content-Type: application/json

{
    "status": "REJECTED"
}
###
PATCH {{baseUrl}}/export/packing/1 HTTP/1.1
Content-Type: application/json

{
    "status": "DONE"
}

###
GET {{baseUrl}}/history/1 HTTP/1.1

###
GET {{baseUrl}}/static/best-seller HTTP/1.1

###
GET {{baseUrl}}/static/worst-seller HTTP/1.1
###
GET {{baseUrl}}/static/most-return HTTP/1.1
